### ISSUE TITLE
Media Backup Album selection is broken

### ISSUE THREAD

**Issue by mfferreira** [s3drive/app#45] opened 2023-11-27 11:51 UTC
Android: 13
s3drive: 1.6.3

When trying to setup the media backup, tapping the Albums "Select" button spits out this error:
```
11-27 12:47:15.056 28965 29535 E MediaMetadataRetrieverJNI: getFrameAtTime: videoFrame is a NULL pointer
11-27 12:47:15.061 28965 29535 W Glide   : Load failed for [content://media/external/video/media/1000016170] with dimensions [512x512]
11-27 12:47:15.061 28965 29535 W Glide   : class f2.q: Failed to load resource
11-27 12:47:15.061 28965 29535 W Glide   : There were 3 root causes:
11-27 12:47:15.061 28965 29535 W Glide   : m2.b0$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
11-27 12:47:15.061 28965 29535 W Glide   : m2.b0$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
11-27 12:47:15.061 28965 29535 W Glide   : m2.b0$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
11-27 12:47:15.061 28965 29535 W Glide   :  call GlideException#logRootCauses(String) for more detail
11-27 12:47:15.061 28965 29535 W Glide   :   Cause (1 of 6): class f2.q: Failed LoadPath{AutoCloseInputStream->Bitmap->Bitmap}, LOCAL
11-27 12:47:15.061 28965 29535 W Glide   :     Cause (1 of 1): class f2.q: Failed DecodePath{AutoCloseInputStream->Bitmap->Bitmap}
11-27 12:47:15.061 28965 29535 W Glide   :   Cause (2 of 6): class f2.q: Failed LoadPath{ParcelFileDescriptorInner->Bitmap->Bitmap}, LOCAL
11-27 12:47:15.061 28965 29535 W Glide   : There was 1 root cause:
11-27 12:47:15.061 28965 29535 W Glide   : m2.b0$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
11-27 12:47:15.061 28965 29535 W Glide   :  call GlideException#logRootCauses(String) for more detail
11-27 12:47:15.061 28965 29535 W Glide   :     Cause (1 of 1): class f2.q: Failed DecodePath{ParcelFileDescriptorInner->Bitmap->Bitmap}
11-27 12:47:15.061 28965 29535 W Glide   : There was 1 root cause:
11-27 12:47:15.061 28965 29535 W Glide   : m2.b0$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
11-27 12:47:15.061 28965 29535 W Glide   :  call GlideException#logRootCauses(String) for more detail
11-27 12:47:15.061 28965 29535 W Glide   :       Cause (1 of 1): class m2.b0$h: MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details
11-27 12:47:15.061 28965 29535 W Glide   :   Cause (3 of 6): class f2.q: Failed LoadPath{AutoCloseInputStream->Bitmap->Bitmap}, LOCAL
11-27 12:47:15.061 28965 29535 W Glide   :     Cause (1 of 1): class f2.q: Failed DecodePath{AutoCloseInputStream->Bitmap->Bitmap}
11-27 12:47:15.061 28965 29535 W Glide   :   Cause (4 of 6): class f2.q: Failed LoadPath{ParcelFileDescriptorInner->Bitmap->Bitmap}, LOCAL
11-27 12:47:15.061 28965 29535 W Glide   : There was 1 root cause:
11-27 12:47:15.061 28965 29535 W Glide   : m2.b0$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
11-27 12:47:15.061 28965 29535 W Glide   :  call GlideException#logRootCauses(String) for more detail
11-27 12:47:15.061 28965 29535 W Glide   :     Cause (1 of 1): class f2.q: Failed DecodePath{ParcelFileDescriptorInner->Bitmap->Bitmap}
11-27 12:47:15.061 28965 29535 W Glide   : There was 1 root cause:
11-27 12:47:15.061 28965 29535 W Glide   : m2.b0$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
11-27 12:47:15.061 28965 29535 W Glide   :  call GlideException#logRootCauses(String) for more detail
11-27 12:47:15.061 28965 29535 W Glide   :       Cause (1 of 1): class m2.b0$h: MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details
11-27 12:47:15.061 28965 29535 W Glide   :   Cause (5 of 6): class f2.q: Failed LoadPath{AssetFileDescriptor->Bitmap->Bitmap}, LOCAL
11-27 12:47:15.061 28965 29535 W Glide   : There was 1 root cause:
11-27 12:47:15.061 28965 29535 W Glide   : m2.b0$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
11-27 12:47:15.061 28965 29535 W Glide   :  call GlideException#logRootCauses(String) for more detail
11-27 12:47:15.061 28965 29535 W Glide   :     Cause (1 of 1): class f2.q: Failed DecodePath{AssetFileDescriptor->Bitmap->Bitmap}
11-27 12:47:15.061 28965 29535 W Glide   : There was 1 root cause:
11-27 12:47:15.061 28965 29535 W Glide   : m2.b0$h(MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details)
11-27 12:47:15.061 28965 29535 W Glide   :  call GlideException#logRootCauses(String) for more detail
11-27 12:47:15.061 28965 29535 W Glide   :       Cause (1 of 1): class m2.b0$h: MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details
11-27 12:47:15.061 28965 29535 W Glide   :   Cause (6 of 6): class f2.q: Failed LoadPath{HierarchicalUri->Bitmap->Bitmap}, LOCAL
11-27 12:47:15.061 28965 29535 W Glide   :     Cause (1 of 1): class f2.q: Failed DecodePath{HierarchicalUri->Bitmap->Bitmap}
11-27 12:47:15.061 28965 29535 I Glide   : Root cause (1 of 3)
11-27 12:47:15.061 28965 29535 I Glide   : m2.b0$h: MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details
11-27 12:47:15.061 28965 29535 I Glide   : 	at m2.b0.f(VideoDecoder.java:44)
11-27 12:47:15.061 28965 29535 I Glide   : 	at m2.b0.b(VideoDecoder.java:99)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.i.c(DecodePath.java:33)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.i.b(DecodePath.java:19)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.i.a(DecodePath.java:1)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.t.b(LoadPath.java:32)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.t.a(LoadPath.java:20)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.h.J(DecodeJob.java:26)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.h.o(DecodeJob.java:11)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.h.n(DecodeJob.java:12)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.h.p(DecodeJob.java:62)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.h.e(DecodeJob.java:46)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.z.g(SourceGenerator.java:42)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.z$a.f(SourceGenerator.java:15)
11-27 12:47:15.061 28965 29535 I Glide   : 	at com.bumptech.glide.load.data.l.e(LocalUriFetcher.java:11)
11-27 12:47:15.061 28965 29535 I Glide   : 	at k2.d$d.e(QMediaStoreUriLoader.java:45)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.z.j(SourceGenerator.java:16)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.z.a(SourceGenerator.java:121)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.h.I(DecodeJob.java:24)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.h.p(DecodeJob.java:91)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.h.e(DecodeJob.java:46)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.z.g(SourceGenerator.java:42)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.z$a.f(SourceGenerator.java:15)
11-27 12:47:15.061 28965 29535 I Glide   : 	at j2.r$a.f(MultiModelLoader.java:5)
11-27 12:47:15.061 28965 29535 I Glide   : 	at com.bumptech.glide.load.data.l.e(LocalUriFetcher.java:11)
11-27 12:47:15.061 28965 29535 I Glide   : 	at j2.r$a.e(MultiModelLoader.java:25)
11-27 12:47:15.061 28965 29535 I Glide   : 	at k2.d$d.e(QMediaStoreUriLoader.java:45)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.z.j(SourceGenerator.java:16)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.z.a(SourceGenerator.java:121)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.h.I(DecodeJob.java:24)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.h.K(DecodeJob.java:49)
11-27 12:47:15.061 28965 29535 I Glide   : 	at f2.h.run(DecodeJob.java:30)
11-27 12:47:15.061 28965 29535 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-27 12:47:15.061 28965 29535 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-27 12:47:15.061 28965 29535 I Glide   : 	at i2.a$d$a.run(GlideExecutor.java:29)
11-27 12:47:15.061 28965 29535 I Glide   : 	at java.lang.Thread.run(Thread.java:1012)
11-27 12:47:15.061 28965 29535 I Glide   : 	at i2.a$c$a.run(GlideExecutor.java:6)
11-27 12:47:15.062 28965 29535 I Glide   : Root cause (2 of 3)
11-27 12:47:15.062 28965 29535 I Glide   : m2.b0$h: MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details
11-27 12:47:15.062 28965 29535 I Glide   : 	at m2.b0.f(VideoDecoder.java:44)
11-27 12:47:15.062 28965 29535 I Glide   : 	at m2.b0.b(VideoDecoder.java:99)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.i.c(DecodePath.java:33)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.i.b(DecodePath.java:19)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.i.a(DecodePath.java:1)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.t.b(LoadPath.java:32)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.t.a(LoadPath.java:20)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.J(DecodeJob.java:26)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.o(DecodeJob.java:11)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.n(DecodeJob.java:12)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.p(DecodeJob.java:62)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.e(DecodeJob.java:46)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.g(SourceGenerator.java:42)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z$a.f(SourceGenerator.java:15)
11-27 12:47:15.062 28965 29535 I Glide   : 	at com.bumptech.glide.load.data.l.e(LocalUriFetcher.java:11)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.j(SourceGenerator.java:16)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.a(SourceGenerator.java:121)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.I(DecodeJob.java:24)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.p(DecodeJob.java:91)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.e(DecodeJob.java:46)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.g(SourceGenerator.java:42)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z$a.f(SourceGenerator.java:15)
11-27 12:47:15.062 28965 29535 I Glide   : 	at com.bumptech.glide.load.data.l.e(LocalUriFetcher.java:11)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.j(SourceGenerator.java:16)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.a(SourceGenerator.java:121)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.I(DecodeJob.java:24)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.p(DecodeJob.java:91)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.e(DecodeJob.java:46)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.g(SourceGenerator.java:42)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z$a.f(SourceGenerator.java:15)
11-27 12:47:15.062 28965 29535 I Glide   : 	at com.bumptech.glide.load.data.l.e(LocalUriFetcher.java:11)
11-27 12:47:15.062 28965 29535 I Glide   : 	at k2.d$d.e(QMediaStoreUriLoader.java:45)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.j(SourceGenerator.java:16)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.a(SourceGenerator.java:121)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.I(DecodeJob.java:24)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.p(DecodeJob.java:91)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.e(DecodeJob.java:46)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.g(SourceGenerator.java:42)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z$a.f(SourceGenerator.java:15)
11-27 12:47:15.062 28965 29535 I Glide   : 	at j2.r$a.f(MultiModelLoader.java:5)
11-27 12:47:15.062 28965 29535 I Glide   : 	at com.bumptech.glide.load.data.l.e(LocalUriFetcher.java:11)
11-27 12:47:15.062 28965 29535 I Glide   : 	at j2.r$a.e(MultiModelLoader.java:25)
11-27 12:47:15.062 28965 29535 I Glide   : 	at k2.d$d.e(QMediaStoreUriLoader.java:45)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.j(SourceGenerator.java:16)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.a(SourceGenerator.java:121)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.I(DecodeJob.java:24)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.K(DecodeJob.java:49)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.run(DecodeJob.java:30)
11-27 12:47:15.062 28965 29535 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-27 12:47:15.062 28965 29535 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-27 12:47:15.062 28965 29535 I Glide   : 	at i2.a$d$a.run(GlideExecutor.java:29)
11-27 12:47:15.062 28965 29535 I Glide   : 	at java.lang.Thread.run(Thread.java:1012)
11-27 12:47:15.062 28965 29535 I Glide   : 	at i2.a$c$a.run(GlideExecutor.java:6)
11-27 12:47:15.062 28965 29535 I Glide   : Root cause (3 of 3)
11-27 12:47:15.062 28965 29535 I Glide   : m2.b0$h: MediaMetadataRetriever failed to retrieve a frame without throwing, check the adb logs for .*MetadataRetriever.* prior to this exception for details
11-27 12:47:15.062 28965 29535 I Glide   : 	at m2.b0.f(VideoDecoder.java:44)
11-27 12:47:15.062 28965 29535 I Glide   : 	at m2.b0.b(VideoDecoder.java:99)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.i.c(DecodePath.java:33)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.i.b(DecodePath.java:19)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.i.a(DecodePath.java:1)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.t.b(LoadPath.java:32)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.t.a(LoadPath.java:20)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.J(DecodeJob.java:26)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.o(DecodeJob.java:11)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.n(DecodeJob.java:12)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.p(DecodeJob.java:62)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.e(DecodeJob.java:46)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.g(SourceGenerator.java:42)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z$a.f(SourceGenerator.java:15)
11-27 12:47:15.062 28965 29535 I Glide   : 	at com.bumptech.glide.load.data.l.e(LocalUriFetcher.java:11)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.j(SourceGenerator.java:16)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.a(SourceGenerator.java:121)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.I(DecodeJob.java:24)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.p(DecodeJob.java:91)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.e(DecodeJob.java:46)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.g(SourceGenerator.java:42)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z$a.f(SourceGenerator.java:15)
11-27 12:47:15.062 28965 29535 I Glide   : 	at com.bumptech.glide.load.data.l.e(LocalUriFetcher.java:11)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.j(SourceGenerator.java:16)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.a(SourceGenerator.java:121)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.I(DecodeJob.java:24)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.p(DecodeJob.java:91)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.e(DecodeJob.java:46)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.g(SourceGenerator.java:42)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z$a.f(SourceGenerator.java:15)
11-27 12:47:15.062 28965 29535 I Glide   : 	at com.bumptech.glide.load.data.l.e(LocalUriFetcher.java:11)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.j(SourceGenerator.java:16)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.a(SourceGenerator.java:121)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.I(DecodeJob.java:24)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.p(DecodeJob.java:91)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.e(DecodeJob.java:46)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.g(SourceGenerator.java:42)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z$a.f(SourceGenerator.java:15)
11-27 12:47:15.062 28965 29535 I Glide   : 	at com.bumptech.glide.load.data.l.e(LocalUriFetcher.java:11)
11-27 12:47:15.062 28965 29535 I Glide   : 	at k2.d$d.e(QMediaStoreUriLoader.java:45)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.j(SourceGenerator.java:16)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.a(SourceGenerator.java:121)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.I(DecodeJob.java:24)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.p(DecodeJob.java:91)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.e(DecodeJob.java:46)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.g(SourceGenerator.java:42)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z$a.f(SourceGenerator.java:15)
11-27 12:47:15.062 28965 29535 I Glide   : 	at j2.r$a.f(MultiModelLoader.java:5)
11-27 12:47:15.062 28965 29535 I Glide   : 	at com.bumptech.glide.load.data.l.e(LocalUriFetcher.java:11)
11-27 12:47:15.062 28965 29535 I Glide   : 	at j2.r$a.e(MultiModelLoader.java:25)
11-27 12:47:15.062 28965 29535 I Glide   : 	at k2.d$d.e(QMediaStoreUriLoader.java:45)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.j(SourceGenerator.java:16)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.z.a(SourceGenerator.java:121)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.I(DecodeJob.java:24)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.K(DecodeJob.java:49)
11-27 12:47:15.062 28965 29535 I Glide   : 	at f2.h.run(DecodeJob.java:30)
11-27 12:47:15.062 28965 29535 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-27 12:47:15.062 28965 29535 I Glide   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-27 12:47:15.062 28965 29535 I Glide   : 	at i2.a$d$a.run(GlideExecutor.java:29)
11-27 12:47:15.062 28965 29535 I Glide   : 	at java.lang.Thread.run(Thread.java:1012)
11-27 12:47:15.062 28965 29535 I Glide   : 	at i2.a$c$a.run(GlideExecutor.java:6)
```

ps: The path `video/media/1000016170` doesn't exist

**Comment by mfferreira** [comment] 2023-11-28 17:01
> Leaving an error aside, can you please let me know what happens when you click: "Select" button? 
Under the search box, there's just a square with a never ending spinner.

> Does the: "Select albums" screen open at all? Does it show albums and assets count? 
Yes, it opens. It does not show any albuns or counters.

> Can you open: "Albums" page (from the bottom nav), does it show media files on your phone? Once you open: "Albums" page, can you click the top right Albums icon in order to open the right-hand drawer menu? Does it show album names and count correctly?
Yes, the drawer slides in with all the albums and respective counters.

**Comment by mfferreira** [comment] 2024-01-03 10:39
Hey @tomekit 

Yes, I have 1.7.0 and in **Media Backup > Albuns** I still get that endless spinner.

**Comment by tomekit** [comment] 2024-05-07 09:59
Sorry for the delay. Is it still an issue for you? Can you please try with the most recent release?

I would appreciate if you could provide your phone model and android version (still 13?).

Thanks

**Comment by mfferreira** [comment] 2024-05-10 14:41
> Sorry for the delay. Is it still an issue for you? Can you please try with the most recent release?
> 
> I would appreciate if you could provide your phone model and android version (still 13?).
> 
> Thanks

Yes, still happening.
Poco F3, Android 13

**Comment by tomekit** [comment] 2024-06-13 08:35
Hi @mfferreira,

I am sorry that it took a while, but I think we've got a solution now.

I would appreciate if you could update to latest (1.9.1) and try again.
 
Thank you for your patience.

Related: https://discord.com/channels/1069654792902815845/1150556652311945367

**Comment by tomekit** [comment] 2024-06-28 19:13
I am going to close this issue and assume it's working now. If it's not working as intended, please comment, so I can reopen. Thanks!

**Closed by tomekit** 2024-06-28 19:13 UTC
