### ISSUE TITLE
upload files failed 

### ISSUE THREAD

**Issue by mix9311** [s3drive/app#25] opened 2023-04-30 13:40 UTC
Why do most of the upload files go wrong, I don't understand the reason.I can’t see the cause of the error at all. Retrying and uploading again will cause errors and failures. If you don’t believe me, you can look at the picture. I really hope that you can improve the service and fix the error! Sometimes I click Retry, but the progress and record of re-uploading the file are still not displayed in the process progress bar|||||  all happens on your s3 drive windows client...
![image](https://user-images.githubusercontent.com/130731540/235355835-66fd3889-e88c-41ab-a72c-baf70d4376ec.png)
![image](https://user-images.githubusercontent.com/130731540/235355843-aac909b4-1830-4b2f-b965-839153d2ad3c.png)
![image](https://user-images.githubusercontent.com/130731540/235355870-62e2f0cd-c652-40e1-9f07-923a8c6d3c6e.png)

**Comment by tomekit** [comment] 2023-04-30 13:45
Thank for this report. Based on your other network related issues: https://github.com/s3drive/app/issues/24 I have reasons to believe that issues that you're experiencing maybe caused by your firewall configuration.
Since you're now running Pro account, you can choose S3 provider that works best for you at your location: https://github.com/s3drive/app/blob/master/S3_PROVIDERS.md

In order to change your provider, please go to: Settings -> Switch Profile and add new account that you would like to use.

**Comment by tomekit** [comment] 2023-04-30 13:54
You can add multiple accounts, but in principle you can only use account at the time. Perhaps in the future such option will be supported.

**Comment by tomekit** [comment] 2023-04-30 13:59
I see, thank you for this idea. We will have it added to our Roadmap as certainly it might be useful to some users.

**Comment by tomekit** [comment] 2023-05-01 16:39
We've added this to roadmap: https://s3drive.canny.io/feature-requests/p/support-using-multiple-accounts-at-once

**Comment by tomekit** [comment] 2023-05-01 20:01
In case you're getting 403 Forbidden, you might also try connecting through proxy. We don't support proxy natively, however one of our users suggested here: https://s3drive.canny.io/feature-requests/p/connect-through-proxy-server that they were successful using Proxifier app on Android.
I am going to close this issue for now, however if you still believe there is an issue on our end we would be happy to investigate that for you. Thanks !

**Closed by tomekit** 2023-05-01 20:01 UTC
